#! /usr/bin/env python

import sys, os
sys.path.append(os.path.dirname(__file__))
sys.path.append(os.path.join(os.path.dirname(__file__), 'TrayLib'))
sys.path.append(
    os.path.join(os.path.dirname(__file__), 'rox-lib', 'ROX-Lib2', 'python')
)

import rox
from mediatray.main import MediaTrayMain, SITE, PROJECT

__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))

rox.setup_app_options(PROJECT, 'Options.xml', SITE)

MediaTrayMain().mainloop(sys.argv)
